### ISSUE TITLE
Browser error in doc

### ISSUE THREAD

**Issue by snarkbe** [noCaptchaAi/chrome#1]
https://github.com/noCaptchaAi/chrome/blame/f86f3091550acca7603fe4e3579db799c6f69f06/README.md#L37

Shouldn't it say "Looking for Firefox Extension ?" ?

**Comment by 404b** [comment]
Thanks. Fixed https://github.com/noCaptchaAi/chrome/commit/b341b5cdff9ef3936ba339868ac83cbb8252f500
